wx:
  mp:
    useRedis: false
    redisConfig:
      host: 39.105.3.42
      port: 6379
      timeout: 2000
      password: Admin@123
    configs:
      - appId: wx04ed95de7aa10343
        secret: 61bcf71af258c722e8357417050c7169
        token: liubo990228
        aesKey: F21n14iiDEzJJEl6K9RI6KqTPNq9tDXy0jA6svCujnf